# 利用神经网络来计算XOR

In [1]:
import numpy as np

In [2]:
from NeuralNetwork import NeuralNetwork

In [3]:
nn = NeuralNetwork([2, 2, 1], 'tanh')

In [4]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])

In [5]:
y = np.array([0,1,1,0])

In [6]:
nn.fit(X, y)

In [7]:
for i in [[0,0], [0,1], [1,0], [1,1]]:
    print(i, nn.predict(i))

[0, 0] [ 0.00270197]
[0, 1] [ 0.99838324]
[1, 0] [ 0.99833157]
[1, 1] [ 0.01245465]


# 利用神经网络来进行手写体的识别

In [8]:
from sklearn.datasets import load_digits

In [9]:
from sklearn.metrics import confusion_matrix, classification_report

In [10]:
from sklearn.preprocessing import LabelBinarizer

In [11]:
from sklearn.cross_validation import train_test_split

/Users/heavenyu1982/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [12]:
digits = load_digits()

In [13]:
X = digits.data

In [14]:
y = digits.target

In [15]:
X = X - X.min()

In [18]:
X = X / X.max()

In [19]:
nn = NeuralNetwork([64, 100, 10], 'logistic')

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [24]:
labels_train = LabelBinarizer().fit_transform(y_train)

In [25]:
labels_test = LabelBinarizer().fit_transform(y_test)

In [26]:
nn.fit(X_train, labels_train, epochs=3500)

In [27]:
predictions = []

In [29]:
for i in range(X_test.shape[0]):
    o = nn.predict(X_test[i])
    predictions.append(np.argmax(o))

In [30]:
print(confusion_matrix(y_test, predictions))

[[45  0  0  0  0  0  0  0  0  0]
 [ 0 44  0  0  0  0  0  0  3  0]
 [ 0  0 43  0  0  0  0  0  0  0]
 [ 0  1  0 45  0  0  0  2  2  0]
 [ 0  3  0  0 43  0  0  1  0  0]
 [ 0  0  0  0  0 46  1  0  0  1]
 [ 0  0  0  0  0  0 44  0  0  0]
 [ 0  0  0  0  1  1  0 44  1  1]
 [ 0  2  0  0  0  0  0  0 40  0]
 [ 0  1  0  2  1  0  0  0  8 24]]
